# Generated by Django 6.1.1 on 2026-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='mushroom_type',
            field=models.CharField(choices=[('white', 'Белый гриб'), ('boletus', 'Подосиновик'), ('birch_bolete', 'Подберёзовик'), ('chanterelle', 'Лисички'), ('honey_fungus', 'Опята'), ('russula', 'Сыроежки'), ('milk_cap', 'Грузди'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Вид грибов'),
        ),
    ]
