# Generated by Django 6.1.1 on 2026-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_mushroomspot_mushroom_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид гриба',
                'verbose_name_plural': 'Виды грибов',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='mushroom_type',
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='mushroom_types',
            field=models.ManyToManyField(blank=True, related_name='spots', to='spots.mushroomtype', verbose_name='Виды грибов'),
        ),
    ]
