# Generated by Django 6.1.1 on 2026-09-19 16:23

import django.db.models.deletion
import spots.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_spotcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=spots.models.comment_photo_upload_path, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='SpotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=spots.models.spot_photo_upload_path, verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spots.mushroomspot')),
            ],
            options={
                'verbose_name': 'Фото места',
                'verbose_name_plural': 'Фото мест',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Лайк')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='spots.spotcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за комментарий',
                'verbose_name_plural': 'Голоса за комментарии',
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='unique_vote_per_user_comment')],
            },
        ),
    ]
